---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01-introduction
      label: "Introduction"
      solveButton: false
    - name: module-02-explore-detected-cves
      label: "Explore Detected CVEs"
      solveButton: false
    - name: module-03-configure-satellite-webhook
      label: "Configure the Satellite Webhook"
      solveButton: false
    - name: module-04-close-the-loop
      label: "Close the Loop: Automatic Remediation"
      solveButton: false
    - name: module-05-verify-closed-loop
      label: "Verify the Closed Loop"
      solveButton: false

tabs:
  - name: "Satellite Web UI"
    url: https://satellite-${GUID}.${DOMAIN}/
    external: false
  - name: "AAP Web UI"
    url: https://aap1-${GUID}.${DOMAIN}/
    external: false
  - name: "satellite.lab terminal"
    path: /wetty_satellite/ssh/root
    port: 443
  - name: "aap1.lab terminal"
    path: /wetty_aap1/ssh/root
    port: 443
  - name: "rhel1.lab terminal"
    path: /wetty_rhel1/ssh/root
    port: 443
  - name: "rhel2.lab terminal"
    path: /wetty_rhel2/ssh/root
    port: 443
